name: CI

on:
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - uses: actions/setup-node@v2 
        with:
          node-version: '16'
          cache: 'npm' 

      - run: npm ci 
      - run: npx npm-run-parallel lint lint:css lint:fmt